/* eslint-disable */
/* Generated by mobile/scripts/generate-local-catalog.mjs — run `node mobile/scripts/generate-local-catalog.mjs` after editing backend seed data. */

import type { Recipe } from "@aipron/shared";

export const LOCAL_CATALOG_RECIPES: Recipe[] = [
  {
    "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli",
    "title": "Crispy-Skinned Salmon with Lemon-Dill Yogurt Sauce + Garlicky Green Beans (30 minutes)",
    "description": "Crispy skin salmon (pan-seared) with a bright lemon-dill yogurt sauce and quick sautéed green beans. Searchable keywords/substitutions: Greek yogurt or sour cream, dill or parsley, salmon or trout, green beans or asparagus, olive oil or avocado oil, Dijon mustard or whole-grain mustard.",
    "heroImage": "https://lh3.googleusercontent.com/aida-public/AB6AXuC7ED_onlyESp89V4yhkqqTnrDp4kNX7u9sCqXFMX3qyzSLbDdxlIEPI2FI6YBdCMGH6P8_jkxqkuGMx9rRJ3-7y7KtJNz_JdTcbL3ApQfx0aref0BPH95Fr7hPToTwT09qtnhapmOKg8QGAg2cBlM4ByxtyBz1L2CliZBrjzeCdLPUNnL2_FnGRFVOkbsr4irwFt3Uk0_QMqhsqNm5KlD7Kcg-D1cH6MdEANIjXJp3GjYZ0n0MIHayrilBHx-vg5I4Z0mJwlS9qPsV",
    "prepTime": 10,
    "cookTime": 20,
    "totalTime": 30,
    "servings": 4,
    "nutrition": {
      "calories": 520,
      "protein": 42,
      "carbs": 14,
      "fat": 33
    },
    "dietaryTags": [
      "gluten-free",
      "low-carb"
    ],
    "cuisine": "Modern American",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-0",
        "name": "Salmon fillets, skin-on (about 1 inch / 2.5 cm thick each)",
        "quantity": 680,
        "unit": "g",
        "notes": "4 fillets at ~170 g each. Substitutions: steelhead trout (1:1), Arctic char (1:1). If skinless, sear 2 minutes less per side and expect less crisp."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-1",
        "name": "Kosher salt",
        "quantity": 1.5,
        "unit": "tsp",
        "notes": "For salmon + beans. If using fine table salt, use 1 tsp total (it’s saltier by volume)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-2",
        "name": "Black pepper, freshly ground",
        "quantity": 0.75,
        "unit": "tsp",
        "notes": "Substitution: 1/2 tsp pre-ground black pepper."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-3",
        "name": "Avocado oil (or extra-virgin olive oil), divided",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "High-heat oil preferred for crisp skin. Substitutions: grapeseed oil (1:1), canola (1:1)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-4",
        "name": "Unsalted butter",
        "quantity": 1,
        "unit": "tbsp",
        "notes": "Optional but recommended for basting. Dairy-free: use 1 tbsp extra oil instead."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-5",
        "name": "Lemon, divided",
        "quantity": 1,
        "unit": "each",
        "notes": "You’ll use 1 tsp zest + 2 tbsp juice for sauce, plus wedges for serving. Bottled juice works in a pinch (2 tbsp)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-6",
        "name": "Plain Greek yogurt (2% or whole)",
        "quantity": 160,
        "unit": "g",
        "notes": "About 2/3 cup. Substitutions: sour cream (1:1), labneh (1:1), dairy-free unsweetened yogurt (1:1; add 1 tsp extra lemon juice)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-7",
        "name": "Dijon mustard",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Substitutions: whole-grain mustard (1:1), yellow mustard (use 2 tsp; milder)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-8",
        "name": "Honey (or maple syrup)",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Balances acidity. Substitutions: maple syrup (1:1), sugar (1 tsp). Omit for very low-carb and increase salt by a pinch."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-9",
        "name": "Fresh dill, finely chopped (or parsley)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Substitutions: flat-leaf parsley (1:1), dried dill (2 tsp; add earlier and let sit 5 minutes)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-10",
        "name": "Garlic cloves, minced",
        "quantity": 3,
        "unit": "cloves",
        "notes": "Substitutions: 3/4 tsp garlic powder added with the beans; or 1 1/2 tbsp jarred minced garlic."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-11",
        "name": "Green beans, trimmed",
        "quantity": 340,
        "unit": "g",
        "notes": "Substitutions: asparagus (340 g; cook 3–5 min), broccolini (340 g; cook 5–7 min)."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-12",
        "name": "Water",
        "quantity": 60,
        "unit": "ml",
        "notes": "Used to steam-finish the beans. Substitution: chicken/veg broth (60 ml) for more flavor."
      },
      {
        "id": "local-crispy-skinned-salmon-with-lemon-dill-yogurt-sauce-garli-ing-13",
        "name": "Red pepper flakes (optional)",
        "quantity": 0.25,
        "unit": "tsp",
        "notes": "Optional heat. Substitution: a pinch of cayenne."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Pat the salmon very dry with paper towels (this is key for crispy skin). Season the flesh side with 1 tsp kosher salt and 1/2 tsp black pepper. Leave at room temp while you prep the sauce (5–10 minutes).",
        "phase": "prep",
        "duration": 600,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Make the lemon-dill yogurt sauce: zest the lemon (1 tsp) and juice it (2 tbsp). In a bowl, whisk together yogurt, lemon zest, lemon juice, Dijon, honey, 1/4 tsp salt, and dill. Taste and adjust: more lemon for brightness, a pinch more salt for balance. Refrigerate until serving.",
        "phase": "prep",
        "duration": 360,
        "timerRequired": false
      },
      {
        "stepNumber": 3,
        "instruction": "Prep the green beans: trim ends. Mince the garlic. Keep beans and garlic separate so the garlic doesn’t burn.",
        "phase": "prep",
        "duration": 240,
        "timerRequired": false
      },
      {
        "stepNumber": 4,
        "instruction": "Crisp the salmon: heat a large skillet over medium-high for 2 minutes. Add 1 tbsp oil. Place salmon skin-side down, then immediately press each fillet with a spatula for 10 seconds to prevent curling. Cook skin-side down 6–8 minutes until the skin is deeply golden and releases easily.",
        "phase": "cook",
        "duration": 480,
        "timerRequired": true
      },
      {
        "stepNumber": 5,
        "instruction": "Flip salmon and baste: reduce heat to medium. Add butter to the pan. Once melted, tilt the pan and spoon butter over the salmon for 30 seconds. Cook 2–4 minutes more (depending on thickness) until the thickest part is just opaque and flakes easily. Transfer salmon to a plate, skin-side up.",
        "phase": "cook",
        "duration": 240,
        "timerRequired": true
      },
      {
        "stepNumber": 6,
        "instruction": "Cook the green beans in the same skillet: keep heat at medium. Add remaining 1 tbsp oil if the pan is dry. Add beans and 1/4 tsp salt, tossing 1 minute. Add garlic and red pepper flakes (optional) and cook 30 seconds until fragrant.",
        "phase": "cook",
        "duration": 90,
        "timerRequired": false
      },
      {
        "stepNumber": 7,
        "instruction": "Steam-finish beans: add water, cover, and steam 3–4 minutes until crisp-tender. Uncover and cook 30–60 seconds to evaporate excess water. Taste and add remaining pepper as needed.",
        "phase": "cook",
        "duration": 270,
        "timerRequired": true
      },
      {
        "stepNumber": 8,
        "instruction": "Serve: spoon lemon-dill yogurt sauce onto plates (or dollop on salmon), add green beans, and finish with lemon wedges. Keep salmon skin facing up so it stays crisp.",
        "phase": "cook",
        "duration": 120,
        "timerRequired": false
      }
    ]
  },
  {
    "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes",
    "title": "One-Pot Lemon-Herb Chicken Thighs with Rice (45 minutes)",
    "description": "Crispy-skinned bone-in chicken thighs, fluffy long-grain rice, and a bright lemon-herb finish in one Dutch oven or deep skillet. Keywords/subs: chicken thighs or drumsticks, jasmine or basmati rice, chicken broth or water, thyme or rosemary, butter or olive oil.",
    "heroImage": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200&auto=format&fit=crop",
    "prepTime": 15,
    "cookTime": 45,
    "totalTime": 60,
    "servings": 4,
    "nutrition": {
      "calories": 540,
      "protein": 38,
      "carbs": 48,
      "fat": 22
    },
    "dietaryTags": [
      "gluten-free"
    ],
    "cuisine": "American",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-0",
        "name": "Bone-in, skin-on chicken thighs",
        "quantity": 900,
        "unit": "g",
        "notes": "~4 large thighs (~225 g each). Subs: bone-in drumsticks (900 g; cook 5 min longer), skinless thighs (reduce oil by 1 tbsp)."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-1",
        "name": "Kosher salt",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Divided for chicken + rice. Fine salt: use 1 1/2 tsp total."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-2",
        "name": "Black pepper, freshly ground",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Sub: 3/4 tsp pre-ground."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-3",
        "name": "Smoked paprika (optional)",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Sub: sweet paprika or omit."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-4",
        "name": "Extra-virgin olive oil",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Sub: avocado oil (1:1)."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-5",
        "name": "Yellow onion, diced",
        "quantity": 1,
        "unit": "each",
        "notes": "~200 g. Sub: shallots (3 medium)."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-6",
        "name": "Garlic cloves, minced",
        "quantity": 4,
        "unit": "cloves",
        "notes": "Sub: 1 tsp garlic powder (add with rice)."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-7",
        "name": "Long-grain white rice (uncooked)",
        "quantity": 300,
        "unit": "g",
        "notes": "~1 1/2 cups. Subs: jasmine (1:1), basmati (1:1; rinse until clear). Do not use instant rice."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-8",
        "name": "Low-sodium chicken broth",
        "quantity": 720,
        "unit": "ml",
        "notes": "Sub: water + 1 tsp bouillon paste, or vegetable broth."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-9",
        "name": "Lemon (zest + juice)",
        "quantity": 1,
        "unit": "each",
        "notes": "Zest 1 tsp; juice 2 tbsp. Sub: 2 tbsp bottled lemon juice."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-10",
        "name": "Fresh thyme leaves (or rosemary, chopped)",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Sub: 3/4 tsp dried thyme (crush between fingers)."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-11",
        "name": "Unsalted butter",
        "quantity": 1,
        "unit": "tbsp",
        "notes": "Finish. Sub: 1 tbsp olive oil."
      },
      {
        "id": "local-one-pot-lemon-herb-chicken-thighs-with-rice-45-minutes-ing-12",
        "name": "Fresh parsley, chopped (optional)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Garnish. Sub: dill."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Pat chicken very dry. Mix 1 tsp salt, 1/2 tsp pepper, and paprika. Season chicken on both sides (reserve a pinch of salt for rice).",
        "duration": 300,
        "timerRequired": false
      },
      {
        "stepNumber": 2,
        "instruction": "Heat a large Dutch oven or deep skillet with lid over medium-high. Add oil. Place chicken skin-side down; cook 6–7 minutes undisturbed until deeply golden. Flip; cook 3 minutes. Remove chicken to a plate (not fully cooked yet).",
        "duration": 600,
        "timerRequired": true
      },
      {
        "stepNumber": 3,
        "instruction": "Reduce heat to medium. Add onion; cook 4 minutes. Add garlic; cook 30 seconds until fragrant.",
        "duration": 270,
        "timerRequired": false
      },
      {
        "stepNumber": 4,
        "instruction": "Stir in rice to coat in fat 1 minute. Add broth, lemon zest, remaining 1 tsp salt, and 1/2 tsp pepper. Scrape browned bits. Nestle chicken skin-side up on top; bring to a simmer.",
        "duration": 180,
        "timerRequired": false
      },
      {
        "stepNumber": 5,
        "instruction": "Cover; reduce heat to low. Simmer 22–25 minutes until rice absorbs liquid and chicken reaches 74°C / 165°F internal.",
        "duration": 1500,
        "timerRequired": true
      },
      {
        "stepNumber": 6,
        "instruction": "Off heat. Rest covered 5 minutes. Drizzle lemon juice; dot butter. Sprinkle thyme and parsley. Fluff rice around chicken and serve.",
        "duration": 300,
        "timerRequired": true
      }
    ]
  },
  {
    "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu",
    "title": "Red Lentil Dal with Tempered Spices + Basmati Rice (40 minutes)",
    "description": "Creamy masoor dal with a garlic-cumin-chili tadka, served with fluffy basmati. Keywords/subs: red lentils or split masoor, ghee or coconut oil (vegan), tomato or canned diced tomato, basmati or jasmine.",
    "heroImage": "https://lh3.googleusercontent.com/aida-public/AB6AXuCP8Mqc_yVBls3rvJz8Se-W2-AW54zy5f4nStc4QsbYt7V_kh6GDsVMYgnAaIpcYvIPRNousQ_VF-yBKWi8p7NBYegHurHmer99huvSa4Z5MkTCiXdQgfxXdGuIuq6RjtD2xB_C_swz1u1F_8BZbAOzA2eehFxgTnipMgjlP3LK3NaeSa0RkfOAOdn-DnwSvXEeefKgiC4rhheKcUZmu2eglH8fmmIuPFUQK5x7ahEr0eEZpsW4Pm97z2fOrolSTT7wbNbknf_zhODf",
    "prepTime": 10,
    "cookTime": 35,
    "totalTime": 45,
    "servings": 4,
    "nutrition": {
      "calories": 420,
      "protein": 18,
      "carbs": 68,
      "fat": 8
    },
    "dietaryTags": [
      "vegetarian",
      "vegan",
      "gluten-free",
      "dairy-free"
    ],
    "cuisine": "Indian",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-0",
        "name": "Red lentils (masoor dal), rinsed",
        "quantity": 240,
        "unit": "g",
        "notes": "~1 1/4 cups. Sub: split red lentils (same weight)."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-1",
        "name": "Water",
        "quantity": 960,
        "unit": "ml",
        "notes": "For dal. Sub: half vegetable broth for depth."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-2",
        "name": "Roma tomatoes, diced",
        "quantity": 200,
        "unit": "g",
        "notes": "~2 medium. Sub: 1 cup canned diced tomatoes + juice."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-3",
        "name": "Yellow onion, finely diced",
        "quantity": 150,
        "unit": "g",
        "notes": "~1 medium."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-4",
        "name": "Fresh ginger, grated",
        "quantity": 15,
        "unit": "g",
        "notes": "~1 tbsp. Sub: 1 tsp ginger paste."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-5",
        "name": "Garlic cloves, minced",
        "quantity": 4,
        "unit": "cloves",
        "notes": "Sub: 1 tsp garlic powder (less punch)."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-6",
        "name": "Ground turmeric",
        "quantity": 1,
        "unit": "tsp"
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-7",
        "name": "Ground cumin",
        "quantity": 1,
        "unit": "tsp"
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-8",
        "name": "Ground coriander",
        "quantity": 1,
        "unit": "tsp"
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-9",
        "name": "Kosher salt",
        "quantity": 1.5,
        "unit": "tsp",
        "notes": "Adjust at end. Low-sodium: start with 1 tsp."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-10",
        "name": "Ghee (or coconut oil for vegan)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "For tadka + finish. Sub: neutral oil."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-11",
        "name": "Cumin seeds",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Sub: 1/2 tsp ground cumin (add with spices)."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-12",
        "name": "Brown mustard seeds",
        "quantity": 0.5,
        "unit": "tsp",
        "notes": "Optional pop. Sub: pinch mustard powder."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-13",
        "name": "Dried red chiles or red pepper flakes",
        "quantity": 0.5,
        "unit": "tsp",
        "notes": "Heat to taste."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-14",
        "name": "Basmati rice (uncooked)",
        "quantity": 200,
        "unit": "g",
        "notes": "Rinse until water runs clear. Cook separately: ~300 ml water, pinch salt, 15 min simmer."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-15",
        "name": "Fresh cilantro, chopped",
        "quantity": 15,
        "unit": "g",
        "notes": "Garnish (~1/4 cup packed). Sub: mint."
      },
      {
        "id": "local-red-lentil-dal-with-tempered-spices-basmati-rice-40-minu-ing-16",
        "name": "Lime, wedges",
        "quantity": 1,
        "unit": "each",
        "notes": "Serve. Sub: lemon."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "In a medium pot, combine lentils, water, tomato, onion, ginger, garlic, turmeric, ground cumin, coriander, and 1 tsp salt. Bring to a boil; skim foam. Reduce to gentle simmer; cook 20–25 minutes, stirring occasionally, until dal is creamy.",
        "duration": 1500,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Meanwhile, cook basmati per package or: combine rinsed rice + 300 ml water + pinch salt; simmer covered 12–15 minutes; rest 5 minutes.",
        "duration": 900,
        "timerRequired": true
      },
      {
        "stepNumber": 3,
        "instruction": "Tadka: in a small skillet, heat ghee/oil over medium-high. Add cumin seeds and mustard seeds; cook 20–30 seconds until fragrant (cover if they pop). Add chiles/red pepper; swirl 15 seconds. Pour over dal; stir.",
        "duration": 120,
        "timerRequired": false
      },
      {
        "stepNumber": 4,
        "instruction": "Taste dal; adjust salt. Serve over rice with cilantro and lime wedges.",
        "duration": 120,
        "timerRequired": false
      }
    ]
  },
  {
    "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m",
    "title": "Beef and Broccoli Stir-Fry with Garlic-Ginger Sauce (25 minutes)",
    "description": "Thin-sliced beef and crisp-tender broccoli in a savory soy-oyster-brown sugar sauce. Keywords/subs: flank or sirloin, broccoli or broccolini, soy sauce or tamari (gluten-free), oyster sauce or mushroom stir-fry sauce.",
    "heroImage": "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&auto=format&fit=crop",
    "prepTime": 15,
    "cookTime": 10,
    "totalTime": 25,
    "servings": 4,
    "nutrition": {
      "calories": 380,
      "protein": 32,
      "carbs": 22,
      "fat": 18
    },
    "dietaryTags": [
      "dairy-free"
    ],
    "cuisine": "Chinese-American",
    "difficulty": "intermediate",
    "ingredients": [
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-0",
        "name": "Flank steak (or sirloin), sliced thin against the grain",
        "quantity": 450,
        "unit": "g",
        "notes": "Sub: skirt steak. Partially freeze 20 min for easier slicing."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-1",
        "name": "Cornstarch (for velveting marinade)",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Sub: arrowroot (1:1)."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-2",
        "name": "Baking soda (tiny pinch, optional tenderizer)",
        "quantity": 0.125,
        "unit": "tsp",
        "notes": "Omit if sensitive to alkaline taste."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-3",
        "name": "Low-sodium soy sauce (or tamari)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "1 tbsp for marinade, rest for sauce."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-4",
        "name": "Toasted sesame oil",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Marinade aroma. Sub: omit."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-5",
        "name": "Broccoli florets",
        "quantity": 450,
        "unit": "g",
        "notes": "Sub: broccolini (450 g)."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-6",
        "name": "Neutral high-heat oil (avocado or grapeseed)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Divided for sear + finish."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-7",
        "name": "Garlic cloves, minced",
        "quantity": 4,
        "unit": "cloves"
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-8",
        "name": "Fresh ginger, grated",
        "quantity": 15,
        "unit": "g",
        "notes": "~1 tbsp."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-9",
        "name": "Oyster sauce",
        "quantity": 3,
        "unit": "tbsp",
        "notes": "Sub: vegetarian oyster sauce or hoisin (reduce sugar)."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-10",
        "name": "Light brown sugar",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Sub: honey (2 tsp)."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-11",
        "name": "Chicken or beef broth",
        "quantity": 120,
        "unit": "ml",
        "notes": "Sub: water."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-12",
        "name": "Cornstarch (for sauce slurry)",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Mixed with 2 tbsp cold water."
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-13",
        "name": "Toasted sesame seeds (optional)",
        "quantity": 1,
        "unit": "tsp"
      },
      {
        "id": "local-beef-and-broccoli-stir-fry-with-garlic-ginger-sauce-25-m-ing-14",
        "name": "Cooked white rice, for serving",
        "quantity": 600,
        "unit": "g",
        "notes": "~4 cups cooked. Sub: noodles."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Toss beef with 1 tbsp soy, cornstarch, baking soda, and sesame oil. Marinate 10 minutes at room temp.",
        "duration": 600,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Whisk sauce: remaining 1 tbsp soy, oyster sauce, brown sugar, broth. Mix slurry: 1 tsp cornstarch + 2 tbsp cold water.",
        "duration": 120,
        "timerRequired": false
      },
      {
        "stepNumber": 3,
        "instruction": "Heat wok or large skillet over high until smoking-hot. Add 1 tbsp oil. Sear beef in one layer 60–90 seconds per side until browned; remove.",
        "duration": 180,
        "timerRequired": true
      },
      {
        "stepNumber": 4,
        "instruction": "Add remaining 1 tbsp oil. Stir-fry broccoli 3–4 minutes until bright green with char spots. Add garlic and ginger; cook 30 seconds.",
        "duration": 270,
        "timerRequired": true
      },
      {
        "stepNumber": 5,
        "instruction": "Return beef. Pour sauce; bring to boil. Stir slurry; drizzle in while tossing until glossy, 30–60 seconds. Serve over rice; top with sesame seeds.",
        "duration": 90,
        "timerRequired": false
      }
    ]
  },
  {
    "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut",
    "title": "Baked Cod with Burst Tomatoes, Olives, and Capers (35 minutes)",
    "description": "Mild white fish in a jammy cherry tomato pan sauce with briny olives and capers. Keywords/subs: cod or haddock or pollock, Kalamata or Castelvetrano olives, white wine or extra broth, gluten-free as written.",
    "heroImage": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200&auto=format&fit=crop",
    "prepTime": 10,
    "cookTime": 25,
    "totalTime": 35,
    "servings": 4,
    "nutrition": {
      "calories": 310,
      "protein": 34,
      "carbs": 12,
      "fat": 12
    },
    "dietaryTags": [
      "gluten-free",
      "low-carb",
      "dairy-free"
    ],
    "cuisine": "Mediterranean",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-0",
        "name": "Cod fillets (or haddock), 1–1.25 inches thick",
        "quantity": 680,
        "unit": "g",
        "notes": "4 portions. Sub: pollock (680 g)."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-1",
        "name": "Kosher salt",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Divided."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-2",
        "name": "Black pepper",
        "quantity": 0.5,
        "unit": "tsp"
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-3",
        "name": "Cherry tomatoes",
        "quantity": 400,
        "unit": "g",
        "notes": "Sub: grape tomatoes."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-4",
        "name": "Garlic cloves, thinly sliced",
        "quantity": 4,
        "unit": "cloves"
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-5",
        "name": "Pitted Kalamata olives, halved",
        "quantity": 60,
        "unit": "g",
        "notes": "Sub: Castelvetrano (60 g)."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-6",
        "name": "Capers, drained",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Rinse if very salty."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-7",
        "name": "Dry white wine",
        "quantity": 60,
        "unit": "ml",
        "notes": "Sub: fish stock or water + 1 tsp lemon juice."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-8",
        "name": "Extra-virgin olive oil",
        "quantity": 3,
        "unit": "tbsp"
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-9",
        "name": "Fresh oregano or thyme leaves",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Sub: 3/4 tsp dried."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-10",
        "name": "Red pepper flakes",
        "quantity": 0.25,
        "unit": "tsp",
        "notes": "Optional."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-11",
        "name": "Lemon, sliced into rounds",
        "quantity": 0.5,
        "unit": "each",
        "notes": "Nest under/around fish."
      },
      {
        "id": "local-baked-cod-with-burst-tomatoes-olives-and-capers-35-minut-ing-12",
        "name": "Fresh parsley, chopped",
        "quantity": 2,
        "unit": "tbsp"
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Heat oven to 220°C / 425°F. Pat cod dry; season with 1/2 tsp salt and pepper.",
        "duration": 120,
        "timerRequired": false
      },
      {
        "stepNumber": 2,
        "instruction": "In a large oven-safe skillet, heat 2 tbsp oil over medium-high. Add tomatoes; cook 4 minutes until blistered. Add garlic, olives, capers, oregano, red pepper; cook 1 minute. Add wine; simmer 1 minute.",
        "duration": 360,
        "timerRequired": true
      },
      {
        "stepNumber": 3,
        "instruction": "Nestle cod on top; tuck lemon slices around. Drizzle remaining 1 tbsp oil; sprinkle remaining 1/2 tsp salt. Bake 12–15 minutes until fish flakes at 63°C / 145°F.",
        "duration": 900,
        "timerRequired": true
      },
      {
        "stepNumber": 4,
        "instruction": "Rest 2 minutes. Garnish parsley; serve with pan juices.",
        "duration": 120,
        "timerRequired": true
      }
    ]
  },
  {
    "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut",
    "title": "Creamy Mushroom Risotto with Parmesan and Thyme (50 minutes)",
    "description": "Classic stovetop risotto: Arborio rice, browned mushrooms, white wine, and Parmigiano. Keywords/subs: Arborio or carnaroli, vegetable broth (vegetarian), white wine or extra broth, Parmesan or pecorino.",
    "heroImage": "https://lh3.googleusercontent.com/aida-public/AB6AXuBoNTBfnEXAiM9jLVxhqxZzHkI2HEDhpqBB-yAsVr9yLX_kwgxhJnPpQUw8IqWzCYepI6eQBmfc5dnbt9drmOhAXQ2DI7IZ42RwpCv429KkW6vtyRSfKOa03KoSWg4BmNnufNnlgtvU2R1ZUL8Mvw4ACWo-vHmpGiE5GiLufa8VUwtJZ6RqxmswsrGk8U4qmpgVB4-sTlkrLBzaMIA-d2qzRmN0qULWI4jJbrqafTC0LoJ0fjt0n2RZjNbIy-b5WJaYgoPgr5V4iaKP",
    "prepTime": 15,
    "cookTime": 35,
    "totalTime": 50,
    "servings": 4,
    "nutrition": {
      "calories": 480,
      "protein": 14,
      "carbs": 62,
      "fat": 16
    },
    "dietaryTags": [
      "vegetarian",
      "gluten-free"
    ],
    "cuisine": "Italian",
    "difficulty": "intermediate",
    "ingredients": [
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-0",
        "name": "Mixed mushrooms (cremini + shiitake), sliced",
        "quantity": 450,
        "unit": "g",
        "notes": "Sub: all cremini."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-1",
        "name": "Arborio rice (uncooked)",
        "quantity": 300,
        "unit": "g",
        "notes": "~1 1/2 cups. Sub: carnaroli."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-2",
        "name": "Low-sodium vegetable broth, warm",
        "quantity": 1.2,
        "unit": "L",
        "notes": "Keep hot on low simmer. Sub: chicken broth."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-3",
        "name": "Dry white wine",
        "quantity": 120,
        "unit": "ml",
        "notes": "Sub: extra broth + 1 tsp white wine vinegar."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-4",
        "name": "Shallots, minced",
        "quantity": 2,
        "unit": "each",
        "notes": "Sub: 1/2 cup diced yellow onion."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-5",
        "name": "Garlic cloves, minced",
        "quantity": 2,
        "unit": "cloves"
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-6",
        "name": "Unsalted butter, divided",
        "quantity": 3,
        "unit": "tbsp",
        "notes": "Sub: olive oil for dairy-free (not as creamy)."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-7",
        "name": "Extra-virgin olive oil",
        "quantity": 1,
        "unit": "tbsp"
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-8",
        "name": "Fresh thyme leaves",
        "quantity": 2,
        "unit": "tsp",
        "notes": "Sub: 3/4 tsp dried thyme."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-9",
        "name": "Kosher salt",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Adjust to broth saltiness."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-10",
        "name": "Black pepper",
        "quantity": 0.5,
        "unit": "tsp"
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-11",
        "name": "Parmigiano-Reggiano, finely grated",
        "quantity": 40,
        "unit": "g",
        "notes": "~1/2 cup. Sub: pecorino Romano (saltier—reduce salt)."
      },
      {
        "id": "local-creamy-mushroom-risotto-with-parmesan-and-thyme-50-minut-ing-12",
        "name": "Flat-leaf parsley, chopped",
        "quantity": 2,
        "unit": "tbsp"
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Heat 1 tbsp butter + 1 tbsp oil in a wide Dutch oven over medium-high. Cook mushrooms 8–10 minutes until deeply browned; season pinch salt. Remove.",
        "duration": 600,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Reduce heat to medium. Add remaining 2 tbsp butter; sweat shallots 3 minutes. Add garlic and thyme; cook 30 seconds.",
        "duration": 210,
        "timerRequired": false
      },
      {
        "stepNumber": 3,
        "instruction": "Toast rice 2 minutes, stirring. Add wine; stir until mostly absorbed.",
        "duration": 180,
        "timerRequired": false
      },
      {
        "stepNumber": 4,
        "instruction": "Add warm broth 120–180 ml at a time, stirring often, letting each addition absorb before the next. 22–26 minutes until rice is creamy with slight bite.",
        "duration": 1560,
        "timerRequired": true
      },
      {
        "stepNumber": 5,
        "instruction": "Fold mushrooms back in. Off heat: stir in Parmesan, salt, pepper. Rest 2 minutes. Top parsley; serve immediately.",
        "duration": 120,
        "timerRequired": true
      }
    ]
  },
  {
    "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick",
    "title": "Chickpea Shawarma Bowl with Tahini-Yogurt Sauce and Pickles (35 minutes)",
    "description": "Roasted spiced chickpeas, cucumber-tomato salad, and a lemony tahini-yogurt drizzle over rice or greens. Keywords/subs: chickpeas or cauliflower, tahini or sunbutter (allergy), Greek yogurt or vegan yogurt, pita or rice.",
    "heroImage": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop",
    "prepTime": 15,
    "cookTime": 25,
    "totalTime": 40,
    "servings": 4,
    "nutrition": {
      "calories": 445,
      "protein": 16,
      "carbs": 58,
      "fat": 18
    },
    "dietaryTags": [
      "vegetarian",
      "gluten-free"
    ],
    "cuisine": "Middle Eastern",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-0",
        "name": "Canned chickpeas, drained and rinsed",
        "quantity": 800,
        "unit": "g",
        "notes": "2 x 400 g cans. Dry well for crispness."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-1",
        "name": "Extra-virgin olive oil",
        "quantity": 3,
        "unit": "tbsp"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-2",
        "name": "Ground cumin",
        "quantity": 2,
        "unit": "tsp"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-3",
        "name": "Smoked paprika",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Sub: sweet paprika."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-4",
        "name": "Ground coriander",
        "quantity": 1,
        "unit": "tsp"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-5",
        "name": "Ground cinnamon",
        "quantity": 0.25,
        "unit": "tsp",
        "notes": "Tiny warmth."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-6",
        "name": "Kosher salt",
        "quantity": 1,
        "unit": "tsp",
        "notes": "Divided for chickpeas + salad."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-7",
        "name": "Black pepper",
        "quantity": 0.5,
        "unit": "tsp"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-8",
        "name": "Cucumber, diced",
        "quantity": 200,
        "unit": "g"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-9",
        "name": "Cherry tomatoes, halved",
        "quantity": 200,
        "unit": "g"
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-10",
        "name": "Red onion, thinly sliced",
        "quantity": 80,
        "unit": "g",
        "notes": "Soak in cold water 10 min to mellow (optional)."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-11",
        "name": "Fresh lemon juice",
        "quantity": 3,
        "unit": "tbsp",
        "notes": "Divided for salad + sauce."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-12",
        "name": "Cooked basmati or warm pita",
        "quantity": 400,
        "unit": "g",
        "notes": "~4 cups rice or 4 pitas (not GF unless GF pita)."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-13",
        "name": "Plain Greek yogurt",
        "quantity": 120,
        "unit": "g",
        "notes": "Sub: unsweetened coconut yogurt."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-14",
        "name": "Tahini, well stirred",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Sub: sunbutter (allergy); thin with water."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-15",
        "name": "Garlic clove, grated",
        "quantity": 1,
        "unit": "cloves",
        "notes": "For sauce."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-16",
        "name": "Warm water (to thin sauce)",
        "quantity": 45,
        "unit": "ml",
        "notes": "As needed."
      },
      {
        "id": "local-chickpea-shawarma-bowl-with-tahini-yogurt-sauce-and-pick-ing-17",
        "name": "Pickles or pickled turnips (optional)",
        "quantity": 60,
        "unit": "g"
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Heat oven to 200°C / 400°F. Toss chickpeas with 2 tbsp oil, cumin, paprika, coriander, cinnamon, 3/4 tsp salt, pepper. Roast 22–25 minutes until crisp outside.",
        "duration": 1500,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Salad: combine cucumber, tomato, onion, 1 tbsp lemon juice, remaining 1/4 tsp salt. Toss; chill.",
        "duration": 300,
        "timerRequired": false
      },
      {
        "stepNumber": 3,
        "instruction": "Sauce: whisk yogurt, tahini, garlic, 2 tbsp lemon juice; thin with water until pourable. Season.",
        "duration": 180,
        "timerRequired": false
      },
      {
        "stepNumber": 4,
        "instruction": "Build bowls: rice or torn pita, roasted chickpeas, salad, drizzle sauce, pickles.",
        "duration": 120,
        "timerRequired": false
      }
    ]
  },
  {
    "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3",
    "title": "Thai Red Coconut Curry with Crispy Tofu and Vegetables (35 minutes)",
    "description": "Firm tofu cubes, red curry paste, coconut milk, bell pepper, and snap peas. Keywords/subs: tofu or chicken thigh cubes (600 g, sear first), fish sauce or soy, Thai basil or cilantro, brown sugar or palm sugar.",
    "heroImage": "https://lh3.googleusercontent.com/aida-public/AB6AXuCP8Mqc_yVBls3rvJz8Se-W2-AW54zy5f4nStc4QsbYt7V_kh6GDsVMYgnAaIpcYvIPRNousQ_VF-yBKWi8p7NBYegHurHmer99huvSa4Z5MkTCiXdQgfxXdGuIuq6RjtD2xB_C_swz1u1F_8BZbAOzA2eehFxgTnipMgjlP3LK3NaeSa0RkfOAOdn-DnwSvXEeefKgiC4rhheKcUZmu2eglH8fmmIuPFUQK5x7ahEr0eEZpsW4Pm97z2fOrolSTT7wbNbknf_zhODf",
    "prepTime": 15,
    "cookTime": 25,
    "totalTime": 40,
    "servings": 4,
    "nutrition": {
      "calories": 410,
      "protein": 18,
      "carbs": 18,
      "fat": 32
    },
    "dietaryTags": [
      "vegetarian",
      "vegan",
      "gluten-free",
      "dairy-free"
    ],
    "cuisine": "Thai",
    "difficulty": "beginner",
    "ingredients": [
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-0",
        "name": "Extra-firm tofu, pressed and cubed 2 cm",
        "quantity": 400,
        "unit": "g",
        "notes": "Press 15 min under weight. Sub: 600 g boneless skinless chicken thigh, 2 cm pieces (cook through to 74°C / 165°F)."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-1",
        "name": "Cornstarch (for tofu)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "For light crust. Omit for chicken."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-2",
        "name": "Neutral oil",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Sear tofu/chicken."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-3",
        "name": "Thai red curry paste",
        "quantity": 3,
        "unit": "tbsp",
        "notes": "Brands vary in heat—start with 2 tbsp if sensitive."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-4",
        "name": "Full-fat coconut milk",
        "quantity": 800,
        "unit": "ml",
        "notes": "2 cans. Shake cans."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-5",
        "name": "Low-sodium vegetable broth",
        "quantity": 120,
        "unit": "ml",
        "notes": "Lightens body. Sub: water."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-6",
        "name": "Light brown sugar",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Sub: palm sugar grated (25 g)."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-7",
        "name": "Fish sauce (or soy sauce for vegan)",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Use tamari if gluten-free vegan."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-8",
        "name": "Lime juice",
        "quantity": 2,
        "unit": "tbsp",
        "notes": "Finish."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-9",
        "name": "Red bell pepper, sliced",
        "quantity": 200,
        "unit": "g"
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-10",
        "name": "Sugar snap peas, trimmed",
        "quantity": 150,
        "unit": "g",
        "notes": "Sub: green beans (150 g)."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-11",
        "name": "Baby corn (optional), drained",
        "quantity": 100,
        "unit": "g"
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-12",
        "name": "Fresh Thai basil or cilantro",
        "quantity": 20,
        "unit": "g",
        "notes": "Torn leaves (~1/2 cup loosely packed)."
      },
      {
        "id": "local-thai-red-coconut-curry-with-crispy-tofu-and-vegetables-3-ing-13",
        "name": "Jasmine rice (uncooked)",
        "quantity": 240,
        "unit": "g",
        "notes": "Cook separately per package (~360 ml water)."
      }
    ],
    "steps": [
      {
        "stepNumber": 1,
        "instruction": "Toss tofu with cornstarch to coat. Heat 2 tbsp oil in large skillet/wok on medium-high. Sear tofu 2–3 minutes per side until golden; remove.",
        "duration": 360,
        "timerRequired": true
      },
      {
        "stepNumber": 2,
        "instruction": "Reduce to medium. Fry curry paste 1–2 minutes until aromatic (add splash coconut milk if sticking).",
        "duration": 120,
        "timerRequired": true
      },
      {
        "stepNumber": 3,
        "instruction": "Pour in remaining coconut milk + broth + sugar + fish sauce. Simmer 5 minutes.",
        "duration": 300,
        "timerRequired": true
      },
      {
        "stepNumber": 4,
        "instruction": "Add bell pepper and baby corn; simmer 4 minutes. Add snap peas; simmer 2 minutes until crisp-tender.",
        "duration": 360,
        "timerRequired": true
      },
      {
        "stepNumber": 5,
        "instruction": "Return tofu; warm 1 minute. Off heat: lime juice and basil/cilantro. Serve over jasmine rice.",
        "duration": 120,
        "timerRequired": false
      }
    ]
  }
];
